### ISSUE TITLE
dr used before it's defined

### ISSUE THREAD

**Issue by rns** [jeffreykegler/Marpa-theory#36]
In 

> RHS(drDR, i) is the i’th symbol on the RHS, where the
> numbering is zero-based.

_dr_ is not yet defined to mean dotted rule, so I'd suggest:

RHS(_rR_, i) is the i’th symbol on the RHS _of rule r_, where the
numbering is zero-based.

**Comment by jeffreykegler** [comment]
Good  catch.  Fixed as of commit 29aa62e2dc5792d81b0225e460e1605e87e66163
Thanks!
