### ISSUE TITLE
trivial grammar vs. nulling grammar

### ISSUE THREAD

**Issue by rns** [jeffreykegler/Marpa-theory#4]
Perhaps change former to latter here and in libmarpa, per http://irclog.perlgeek.de/marpa/2015-03-08#i_10243670?

**Comment by jeffreykegler** [comment]
The Marpa theory paper is "between two horses".  I started a major
revision, which is stalled and which I don't know when I can get back to.
From that point of view, it doesn't make sense to do more than correct
typos and obvious errors in the current version.

**Comment by rns** [comment]
Ok, got it.
