### ISSUE TITLE
License missing from repo

### ISSUE THREAD

**Issue by karan** [jeffreykegler/Marpa-theory#5]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by jeffreykegler** [comment]
The only serious content is in recce.ltx, which already had license info.   Nonetheless, no harm in making things clearer.  Closed via the above referenced commit.  Thanks!
