### ISSUE TITLE
EBNF

### ISSUE THREAD

**Issue by ArsenShnurkov** [jeffreykegler/Marpa-theory#69]
Earley paper is written on basis of "simple rewrite rules". They are similar to BNF. EBNF is bit more complex - contains repetitions, optional parts, alternatives. Wikipedia recommends to convert EBNF into BNF by providing additional temporary rules. This is pose trouble for me - how to provide error feedback in terms of source grammar, having earley's structures, which are described in simplier terms. There is a paper 2007-05, https://www.researchgate.net/publication/226022677_An_extension_of_Earley's_algorithm_for_extended_grammars which is not available publicly. And your theory doesn't contain the word EBNF (github search doesn't find it)

https://groups.google.com/forum/#!msg/marpa-parser/R2fzDCrazac/O0Sh8yAjnoEJ
"if you look at EBNF, it is very clear that its inventors had zero expectation that anyone would ever use it"

**Comment by jeffreykegler** [comment]
Thanks for the input.  I'm closing the issue, because this is best discussed on the IRC channel (as is being done) or in the mailing list.
